using System.Globalization;
using WindowsGSH.Core.Modules;
namespace WindowsGSH.Modules.AbioticFactor;
internal static class AbioticSandboxSettings
{
 private static string PathFor(ServerInstance i)=>Path.Combine(i.InstallPath,"AbioticFactor","Saved","SaveGames","Server","Worlds",Get(i,"server.world","Cascade"),"SandboxSettings.ini");
 public static Task<IReadOnlyDictionary<string,object?>> ReadAsync(ServerInstance i,CancellationToken ct){ct.ThrowIfCancellationRequested();var result=new Dictionary<string,object?>();var path=PathFor(i);if(!File.Exists(path))return Task.FromResult<IReadOnlyDictionary<string,object?>>(result);var values=File.ReadLines(path).Select(x=>x.Split('=',2)).Where(x=>x.Length==2).ToDictionary(x=>x[0].Trim(),x=>x[1].Trim(),StringComparer.OrdinalIgnoreCase);Copy(values,result,"GameDifficulty","gameplay.difficulty");CopyBool(values,result,"HardcoreMode","gameplay.hardcore");CopyBool(values,result,"LootRespawnEnabled","gameplay.lootRespawn");CopyDecimal(values,result,"DayNightCycleSpeedMultiplier","gameplay.dayNightSpeed");CopyDecimal(values,result,"EnemyHealthMultiplier","gameplay.enemyHealthMultiplier");CopyDecimal(values,result,"PlayerXPGainMultiplier","gameplay.playerXpMultiplier");return Task.FromResult<IReadOnlyDictionary<string,object?>>(result);}
 public static Task WriteAsync(ServerInstance i,CancellationToken ct){ct.ThrowIfCancellationRequested();var path=PathFor(i);Directory.CreateDirectory(Path.GetDirectoryName(path)!);var lines=File.Exists(path)?File.ReadAllLines(path).ToList():new List<string>{"[SandboxSettings]"};Set(lines,"GameDifficulty",Get(i,"gameplay.difficulty","1"));Set(lines,"HardcoreMode",Bool(i,"gameplay.hardcore",false));Set(lines,"LootRespawnEnabled",Bool(i,"gameplay.lootRespawn",false));Set(lines,"DayNightCycleSpeedMultiplier",Dec(i,"gameplay.dayNightSpeed",1,.1m,3));Set(lines,"EnemyHealthMultiplier",Dec(i,"gameplay.enemyHealthMultiplier",1,.1m,5));Set(lines,"PlayerXPGainMultiplier",Dec(i,"gameplay.playerXpMultiplier",1,.1m,5));File.WriteAllLines(path,lines);return Task.CompletedTask;}
 private static void Set(List<string>l,string k,string v){for(var n=0;n<l.Count;n++){var p=l[n].Split('=',2);if(p.Length==2&&p[0].Trim().Equals(k,StringComparison.OrdinalIgnoreCase)){l[n]=$"{k}={v}";return;}}l.Add($"{k}={v}");}private static void Copy(IDictionary<string,string>s,IDictionary<string,object?>d,string f,string t){if(s.TryGetValue(f,out var v))d[t]=v;}private static void CopyBool(IDictionary<string,string>s,IDictionary<string,object?>d,string f,string t){if(s.TryGetValue(f,out var v)&&bool.TryParse(v,out var b))d[t]=b;}private static void CopyDecimal(IDictionary<string,string>s,IDictionary<string,object?>d,string f,string t){if(s.TryGetValue(f,out var v)&&decimal.TryParse(v,NumberStyles.Number,CultureInfo.InvariantCulture,out var n))d[t]=n;}private static string Get(ServerInstance i,string k,string f)=>i.Settings.TryGetValue(k,out var v)&&v is not null?v.ToString()!.Trim():f;private static string Bool(ServerInstance i,string k,bool f)=>bool.TryParse(Get(i,k,f.ToString()),out var v)?v.ToString().ToLowerInvariant():f.ToString().ToLowerInvariant();private static string Dec(ServerInstance i,string k,decimal f,decimal min,decimal max)=>decimal.TryParse(Get(i,k,f.ToString(CultureInfo.InvariantCulture)),NumberStyles.Number,CultureInfo.InvariantCulture,out var v)&&v>=min&&v<=max?v.ToString(CultureInfo.InvariantCulture):f.ToString(CultureInfo.InvariantCulture);
}
